export const SET_CLASS = '@@FLIGHT/SET_CLASS';
export const SET_FLEXDATE = '@@FLIGHT/SET_FLEXDATE';
export const SET_FROMDATE = '@@FLIGHT/SET_FROMDATE';
export const SET_TODATE = '@@FLIGHT/SET_TODATE';
export const SET_PASSENGERS = '@@FLIGHT/SET_PASSENGERS';
